-- MySQL Script generated by MySQL Workbench
-- Wed Nov  5 16:04:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sigedex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sigedex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sigedex` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sigedex` ;

-- -----------------------------------------------------
-- Table `sigedex`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`departamentos` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `dni` INT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_usuario` VARCHAR(20) NOT NULL,
  `estado` ENUM('activo', 'inactivo') NULL DEFAULT 'activo',
  `id_departamento` INT NULL DEFAULT NULL,
  `id_rol` INT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ultimo_acceso` TIMESTAMP NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `dni_cuit` (`dni` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  INDEX `usuario_ibfk_1` (`id_departamento` ASC),
  INDEX `usuario_ibfk_2` (`id_rol` ASC),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `sigedex`.`departamentos` (`id_departamento`),
  CONSTRAINT `usuario_ibfk_2`
    FOREIGN KEY (`id_rol`)
    REFERENCES `sigedex`.`roles` (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`auditoria_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`auditoria_sistema` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `accion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_origen` VARCHAR(50) NULL DEFAULT NULL,
  `nivel` ENUM('info', 'warning', 'error') NULL DEFAULT 'info',
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_auditoria`),
  INDEX `id_usuario` (`id_usuario` ASC),
  CONSTRAINT `auditoria_sistema_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`expedientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`expedientes` (
  `id_expediente` INT NOT NULL AUTO_INCREMENT,
  `numero_expediente` VARCHAR(50) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `estado_actual` ENUM('en revisión', 'aprobado', 'rechazado', 'archivado') NULL DEFAULT 'en revisión',
  `id_usuario_presentante` INT NOT NULL,
  `id_profesional_asignado` INT NULL DEFAULT NULL,
  `tipo_expediente` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `fecha_cierre` DATETIME NULL DEFAULT NULL,
  `prioridad` ENUM('alta', 'media', 'baja') NULL DEFAULT 'media',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ubicacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_expediente`),
  UNIQUE INDEX `numero_expediente` (`numero_expediente` ASC),
  INDEX `id_usuario_presentante` (`id_usuario_presentante` ASC),
  INDEX `id_profesional_asignado` (`id_profesional_asignado` ASC),
  CONSTRAINT `expedientes_ibfk_1`
    FOREIGN KEY (`id_usuario_presentante`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`),
  CONSTRAINT `expedientes_ibfk_2`
    FOREIGN KEY (`id_profesional_asignado`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`consultas_en_tiempo_real`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`consultas_en_tiempo_real` (
  `id_consulta` INT NOT NULL AUTO_INCREMENT,
  `id_expediente` INT NULL DEFAULT NULL,
  `id_usuario_emisor` INT NULL DEFAULT NULL,
  `id_usuario_receptor` INT NULL DEFAULT NULL,
  `mensaje` TEXT NULL DEFAULT NULL,
  `fecha_envio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('pendiente', 'respondida', 'cerrada') NULL DEFAULT 'pendiente',
  `canal_id` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_consulta`),
  INDEX `id_expediente` (`id_expediente` ASC),
  INDEX `id_usuario_emisor` (`id_usuario_emisor` ASC),
  INDEX `id_usuario_receptor` (`id_usuario_receptor` ASC),
  CONSTRAINT `consultas_en_tiempo_real_ibfk_1`
    FOREIGN KEY (`id_expediente`)
    REFERENCES `sigedex`.`expedientes` (`id_expediente`)
    ON DELETE CASCADE,
  CONSTRAINT `consultas_en_tiempo_real_ibfk_2`
    FOREIGN KEY (`id_usuario_emisor`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`),
  CONSTRAINT `consultas_en_tiempo_real_ibfk_3`
    FOREIGN KEY (`id_usuario_receptor`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`documentos` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `id_expediente` INT NOT NULL,
  `nombre_archivo` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  `ruta_archivo` VARCHAR(255) NOT NULL,
  `fecha_subida` DATETIME NOT NULL,
  `subido_por` INT NOT NULL,
  `tamaño_archivo` BIGINT NULL DEFAULT NULL,
  `hash_integridad` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `id_expediente` (`id_expediente` ASC),
  INDEX `subido_por` (`subido_por` ASC),
  CONSTRAINT `documentos_ibfk_1`
    FOREIGN KEY (`id_expediente`)
    REFERENCES `sigedex`.`expedientes` (`id_expediente`)
    ON DELETE CASCADE,
  CONSTRAINT `documentos_ibfk_2`
    FOREIGN KEY (`subido_por`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`firmas_digitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`firmas_digitales` (
  `id_firma` INT NOT NULL AUTO_INCREMENT,
  `id_expediente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_firma` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `hash_documento` VARCHAR(255) NULL DEFAULT NULL,
  `metodo_firma` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_firma`),
  INDEX `id_expediente` (`id_expediente` ASC),
  INDEX `id_usuario` (`id_usuario` ASC),
  CONSTRAINT `firmas_digitales_ibfk_1`
    FOREIGN KEY (`id_expediente`)
    REFERENCES `sigedex`.`expedientes` (`id_expediente`),
  CONSTRAINT `firmas_digitales_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`historial_expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`historial_expediente` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `id_expediente` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `accion` VARCHAR(255) NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `id_usuario_responsable` INT NULL DEFAULT NULL,
  `id_departamento` INT NULL DEFAULT NULL,
  `tipo_accion` ENUM('asignación', 'revisión', 'firma', 'observación', 'cierre') NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_historial`),
  INDEX `id_expediente` (`id_expediente` ASC),
  INDEX `id_usuario_responsable` (`id_usuario_responsable` ASC),
  INDEX `id_departamento` (`id_departamento` ASC),
  CONSTRAINT `historial_expediente_ibfk_1`
    FOREIGN KEY (`id_expediente`)
    REFERENCES `sigedex`.`expedientes` (`id_expediente`)
    ON DELETE CASCADE,
  CONSTRAINT `historial_expediente_ibfk_2`
    FOREIGN KEY (`id_usuario_responsable`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`),
  CONSTRAINT `historial_expediente_ibfk_3`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `sigedex`.`departamentos` (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`logs` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_expediente` INT NULL DEFAULT NULL,
  `accion` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_hora` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `nivel` ENUM('info', 'warning', 'error') NULL DEFAULT 'info',
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_log`),
  INDEX `id_usuario` (`id_usuario` ASC),
  INDEX `id_expediente` (`id_expediente` ASC),
  CONSTRAINT `logs_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`),
  CONSTRAINT `logs_ibfk_2`
    FOREIGN KEY (`id_expediente`)
    REFERENCES `sigedex`.`expedientes` (`id_expediente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`notificaciones` (
  `id_notificacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `mensaje` TEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_envio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `leida` TINYINT(1) NULL DEFAULT '0',
  `canal` ENUM('sistema', 'email', 'push') NULL DEFAULT 'sistema',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_notificacion`),
  INDEX `id_usuario` (`id_usuario` ASC),
  CONSTRAINT `notificaciones_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`observaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`observaciones` (
  `id_observacion` INT NOT NULL AUTO_INCREMENT,
  `id_expediente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  `fecha_hora` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('pendiente', 'revisada', 'cerrada') NULL DEFAULT 'pendiente',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_observacion`),
  INDEX `id_expediente` (`id_expediente` ASC),
  INDEX `id_usuario` (`id_usuario` ASC),
  CONSTRAINT `observaciones_ibfk_1`
    FOREIGN KEY (`id_expediente`)
    REFERENCES `sigedex`.`expedientes` (`id_expediente`),
  CONSTRAINT `observaciones_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`pagos` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_expediente` INT NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `fecha_pago` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `metodo_pago` ENUM('tarjeta', 'transferencia', 'otros') NULL DEFAULT 'tarjeta',
  `estado_pago` ENUM('pendiente', 'confirmado', 'fallido') NULL DEFAULT 'pendiente',
  `referencia_pasarela` VARCHAR(255) NULL DEFAULT NULL COMMENT 'ID de confirmación devuelto por la pasarela',
  PRIMARY KEY (`id_pago`),
  INDEX `id_usuario` (`id_usuario` ASC),
  INDEX `id_expediente` (`id_expediente` ASC),
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sigedex`.`usuario` (`id_usuario`),
  CONSTRAINT `pagos_ibfk_2`
    FOREIGN KEY (`id_expediente`)
    REFERENCES `sigedex`.`expedientes` (`id_expediente`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`permisos` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigedex`.`rol_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedex`.`rol_permisos` (
  `id_rol` INT NOT NULL,
  `id_permiso` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `id_permiso`),
  INDEX `id_permiso` (`id_permiso` ASC),
  CONSTRAINT `rol_permisos_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `sigedex`.`roles` (`id_rol`)
    ON DELETE CASCADE,
  CONSTRAINT `rol_permisos_ibfk_2`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `sigedex`.`permisos` (`id_permiso`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
